# Generated by Django 2.0.6 on 2019-03-22 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherspot',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
