# Generated by Django 2.0.6 on 2018-07-04 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherspot',
            name='created_date',
        ),
        migrations.AddField(
            model_name='weatherspot',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
